name: Pull Request CI

on:
  pull_request:
    branches: [ main, master ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install --system -e .
          uv pip install --system ".[dev]" pytest pytest-asyncio pyright
          
      - name: Static type checking
        run: pyright src
        
      - name: Run tests
        run: pytest tests/ -v
        
      - name: Build Docker image
        run: docker build -t mcp-remote-macos-use:test . 